name: CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
      - name: Check formatting
        run: zig fmt --check src/*.zig build.zig
      - name: Run Tests
        run: zig build test
